/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
static yyconst short int yy_accept[302] =
    {   0,
       64,   64,   70,   69,   64,   65,   64,   69,   69,   69,
       69,   69,   69,   37,   35,   21,   36,   69,   38,   62,
       62,   34,   69,   41,   68,   18,   19,   39,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   16,   69,   17,   64,   64,    0,
       13,   12,    0,   60,    0,    0,    0,   14,   15,    0,
        0,    0,   62,   61,    0,    0,    0,   62,    0,   20,
        0,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   51,   68,
       68,   68,   68,   68,   68,   68,   68,   68,    0,   68,

       68,   68,   68,   68,   10,   11,    0,   61,    0,    1,
        0,    0,   63,    0,   67,   68,   68,   68,   68,   49,
        4,   68,   68,   68,   68,   68,    0,   68,   68,   68,
       68,   68,   68,   40,   68,   68,   68,   68,   68,   68,
       68,    0,   48,   68,   68,   68,   68,   50,    0,    0,
        1,    2,   63,    0,   68,   68,   68,   68,   68,   68,
       44,   68,   68,    0,    0,   68,    0,   68,   31,   42,
       68,   68,   68,   68,   68,   59,   68,   68,    0,   68,
       68,   68,   68,    0,    0,   63,    0,    0,   68,    0,
       68,   68,   68,   54,   68,    0,    0,   43,    5,   68,

        0,   52,   33,   47,   30,   68,   68,   29,    0,   68,
       68,   68,   68,    0,    0,   63,    0,    0,   68,    0,
       24,   68,   68,    0,   28,    0,    0,   68,    0,   68,
        0,    0,    0,   68,    9,   68,   66,    0,   63,    0,
        0,   68,    7,   58,    0,    6,   27,    0,   68,   46,
       53,    0,    3,    0,    0,   26,    0,    0,   61,    0,
        0,   22,    0,   45,   23,    0,    0,    0,    0,   61,
       61,   61,   32,    8,   57,    0,    0,    0,   61,   61,
       61,   55,    0,    0,   61,   61,   61,   56,   25,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,

        0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    1,    8,    1,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   22,   22,   22,   24,   25,   25,   25,   26,   25,
       25,   27,   25,   28,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   29,   25,   25,   25,   25,   25,   25,
       30,    1,   31,   32,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       48,   49,   50,   51,   52,   53,   54,   55,   56,   25,
       57,   25,   58,   59,   60,   61,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[62] =
    {   0,
        1,    2,    3,    2,    2,    1,    2,    1,    2,    2,
        2,    2,    2,    1,    4,    1,    4,    4,    4,    2,
        1,    2,    1,    4,    4,    4,    4,    4,    4,    1,
        1,    1,    2,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    2,    2,    2,
        2
    } ;

static yyconst short int yy_base[306] =
    {   0,
        0,    0,  591,  592,   60,  592,   61,   61,  584,   55,
      581,  579,  577,  592,   55,  592,   63,   66,   55,   71,
       76,  592,  579,  592,  570,  592,  592,  552,   61,   72,
       60,   77,   82,   84,   83,   88,   85,   89,   90,   92,
       87,   94,  106,   96,  592,  524,  592,  108,  139,  521,
      592,  592,  575,  574,  567,  564,  524,  592,  592,  132,
      146,  139,  151,  154,  515,  514,  157,  162,  170,  592,
      533,  558,  113,  145,  163,  137,  152,  138,  168,  170,
      171,  173,  177,  178,  179,  180,  181,  183,  557,  186,
      188,  187,  184,  189,  190,  192,  194,  191,  519,  198,

      204,  197,  205,  202,  592,  592,  517,  211,  233,    0,
      508,  552,  236,  239,  592,  208,  219,  223,  225,  552,
      551,  226,  231,  245,  246,  247,  224,  249,  253,  250,
      254,  256,  258,  550,  257,  263,  264,  265,  267,  270,
      269,  511,  548,  272,  274,  275,  277,  547,  527,  281,
        0,  592,  292,  295,  289,  288,  303,  304,  278,  279,
      545,  305,  310,  511,  516,  312,  520,  313,  541,  314,
      316,  317,  319,  322,  320,  540,  323,  324,  520,  326,
      329,  331,  328,  517,  334,  337,  340,  509,  334,  515,
      330,  333,  345,  535,  355,  498,  503,  357,  592,  361,

      509,  531,  530,  529,  528,  365,  364,  527,  490,  366,
      369,  367,  370,  499,  374,  377,  391,  491,  371,  497,
      522,  372,  383,  497,  592,  490,  496,  385,  483,  374,
      485,  478,   82,  386,  515,  391,  592,  395,  408,  413,
      492,  400,  592,  513,  482,  592,  592,  476,  402,  592,
      510,  470,  592,  475,  481,  506,  483,  416,  419,  430,
      470,  430,  405,  592,  427,  394,  388,  380,  389,  433,
      436,  439,  592,  592,  592,  374,  367,  366,  442,  445,
      448,  592,  167,   84,  451,  454,  457,  592,  592,  460,
      463,  466,  469,  472,  475,  478,  481,  484,  487,  490,

      592,  509,  109,  512,  516
    } ;

static yyconst short int yy_def[306] =
    {   0,
      301,    1,  301,  301,  301,  301,  301,  301,  302,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  303,  301,  301,  301,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  301,  301,  301,  301,  301,  301,
      301,  301,  302,  302,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  304,  301,  301,  301,  301,
      301,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  301,  303,

      303,  303,  303,  303,  301,  301,  301,  301,  301,  305,
      304,  301,  301,  301,  301,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  301,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  301,  303,  303,  303,  303,  303,  303,  301,  301,
      305,  301,  301,  301,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  301,  301,  303,  301,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  301,  303,
      303,  303,  303,  301,  301,  301,  301,  301,  303,  301,
      303,  303,  303,  303,  303,  301,  301,  303,  301,  303,

      301,  303,  303,  303,  303,  303,  303,  303,  301,  303,
      303,  303,  303,  301,  301,  301,  301,  301,  303,  301,
      303,  303,  303,  301,  301,  301,  301,  303,  301,  303,
      301,  301,  301,  303,  303,  303,  301,  301,  301,  301,
      301,  303,  301,  303,  301,  301,  301,  301,  303,  301,
      303,  301,  301,  301,  301,  303,  301,  301,  301,  301,
      301,  303,  301,  301,  303,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,

        0,  301,  301,  301,  301
    } ;

static yyconst short int yy_nxt[654] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   22,
       23,    4,   24,   25,   25,   25,   25,   25,   25,   26,
       27,   28,    4,   29,   30,   31,   32,   33,   34,   35,
       25,   36,   37,   25,   38,   39,   40,   41,   42,   25,
       25,   43,   44,   25,   25,   25,   25,   45,   46,   47,
        4,   48,   48,   48,   49,   51,   55,   52,   56,   60,
       65,   61,   61,   61,   71,   71,   50,   62,   57,   63,
       63,   63,   64,   64,   64,   67,   71,   63,   63,   63,
       67,   71,   63,   68,   68,   73,   71,   71,   71,   71,

       75,   71,   71,   71,   71,   74,   71,   76,   71,   48,
       71,   48,   72,   69,   77,   66,  254,  255,   78,   81,
       71,  289,   86,   95,   79,   92,   88,   71,   82,  104,
       83,   80,   87,   84,   85,   89,   90,   91,   99,   93,
       48,   96,   49,   94,   97,   98,  116,  100,  108,  108,
      108,   71,   71,  101,   50,   64,   64,   64,  102,   71,
      109,  103,   61,   61,   61,   67,   71,   63,   63,   63,
       64,   64,   64,  113,  113,  113,   67,   71,   63,   68,
       68,  114,   71,  114,   71,   71,  117,   71,  120,  122,
      121,   71,   71,   71,   71,   71,  118,   71,   71,   69,

       71,   71,   71,   71,   71,   71,   71,  124,   71,  127,
      119,   71,   71,  135,  288,  128,   71,  131,   71,   71,
      126,  123,   71,  125,  134,  133,  138,  108,  108,  108,
      145,  129,  130,   71,  132,  140,  136,   71,  144,   71,
       71,  137,  139,  141,  143,   71,  147,  146,  148,  150,
      150,  150,  153,  153,  153,  154,  154,  154,  155,   71,
       71,   71,  164,   71,   71,  160,  158,   71,   71,  156,
       71,   71,   71,  157,  159,  171,  165,   71,   71,   71,
      163,   71,  166,   71,   71,  167,   71,  168,   71,   71,
      175,   71,   71,   71,  161,  169,  162,  185,  185,  185,

      173,  174,   71,   71,  172,  180,  178,  170,  186,  186,
      186,  187,  187,  187,  176,  177,  182,   71,   71,   71,
      181,  188,  192,  193,   71,  189,   71,   71,   71,  183,
       71,   71,  202,   71,   71,  190,   71,   71,   71,  191,
       71,  200,   71,   71,   71,   71,  201,   71,   71,  194,
      215,  215,  215,  216,  216,  216,  217,  217,  217,   71,
      207,  219,  195,  213,  198,  211,  222,  221,  204,   71,
      205,   71,  208,  203,  206,   71,  210,  212,   71,   71,
       71,   71,  223,   71,   71,   71,   71,  224,   71,  227,
      238,  238,  238,  239,  239,  239,  231,   71,  233,   71,

       71,  228,  230,  234,  242,   71,  235,  240,  240,  240,
      236,  258,  258,  258,   71,  245,   71,  284,  249,  283,
      251,  282,  278,  257,  259,  259,  259,  277,  244,  260,
      260,  260,  270,  270,  270,  271,  271,  271,  276,  275,
      262,   71,  256,  274,   71,  265,  272,  272,  272,  279,
      279,  279,  280,  280,  280,  281,  281,  281,  285,  285,
      285,  286,  286,  286,  287,  287,  287,  290,  290,  290,
      291,  291,  291,  292,  292,  292,  293,  293,  293,  294,
      294,  294,  295,  295,  295,  296,  296,  296,  297,  297,
      297,  298,  298,  298,  299,  299,  299,  297,  297,  297,

      300,  300,  300,  299,  299,  299,  300,  300,  300,   53,
       53,  273,   53,  111,  111,  111,  151,  151,  269,  151,
       71,  268,  267,  266,   71,  264,  263,   71,  261,   71,
      253,  252,  250,  248,  247,  246,   71,  243,  241,  237,
      232,   71,   71,   71,   71,   71,  229,  226,  225,   71,
      220,  218,  214,  209,   71,   71,  199,  197,  196,   71,
      184,   71,   71,  179,   71,   71,   71,  152,  112,  149,
      142,   71,   71,  115,  112,  110,  107,  106,  105,   54,
       54,   66,   51,   51,   71,   70,   59,   58,   51,   54,
      301,    3,  301,  301,  301,  301,  301,  301,  301,  301,

      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301
    } ;

static yyconst short int yy_chk[654] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    7,    5,    7,    8,   10,    8,   10,   15,
       19,   15,   15,   15,   31,   29,    7,   17,   10,   17,
       17,   17,   18,   18,   18,   20,   30,   20,   20,   20,
       21,   32,   21,   21,   21,   29,   33,   35,   34,   37,

       31,   41,   36,   38,   39,   30,   40,   31,   42,   48,
       44,   48,  303,   21,   32,   19,  233,  233,   32,   34,
       43,  284,   37,   41,   32,   40,   38,   73,   34,   44,
       35,   33,   37,   35,   36,   38,   38,   39,   43,   40,
       49,   42,   49,   40,   42,   42,   73,   43,   60,   60,
       60,   76,   78,   43,   49,   62,   62,   62,   43,   74,
       61,   43,   61,   61,   61,   63,   77,   63,   63,   63,
       64,   64,   64,   67,   67,   67,   68,   75,   68,   68,
       68,   69,   79,   69,   80,   81,   74,   82,   76,   78,
       77,   83,   84,   85,   86,   87,   75,   88,   93,   68,

       90,   92,   91,   94,   95,   98,   96,   80,   97,   83,
       75,  102,  100,   92,  283,   84,  104,   87,  101,  103,
       82,   79,  116,   81,   91,   90,   95,  108,  108,  108,
      102,   85,   86,  117,   88,   97,   93,  118,  101,  119,
      122,   94,   96,   98,  100,  123,  103,  102,  104,  109,
      109,  109,  113,  113,  113,  114,  114,  114,  116,  124,
      125,  126,  127,  128,  130,  123,  119,  129,  131,  117,
      132,  135,  133,  118,  122,  133,  127,  136,  137,  138,
      126,  139,  128,  141,  140,  129,  144,  130,  145,  146,
      138,  147,  159,  160,  124,  131,  125,  150,  150,  150,

      136,  137,  156,  155,  135,  144,  141,  132,  153,  153,
      153,  154,  154,  154,  139,  140,  146,  157,  158,  162,
      145,  155,  159,  160,  163,  156,  166,  168,  170,  147,
      171,  172,  171,  173,  175,  157,  174,  177,  178,  158,
      180,  168,  183,  181,  191,  182,  170,  192,  189,  162,
      185,  185,  185,  186,  186,  186,  187,  187,  187,  193,
      177,  189,  163,  183,  166,  181,  192,  191,  173,  195,
      174,  198,  178,  172,  175,  200,  180,  182,  207,  206,
      210,  212,  193,  211,  213,  219,  222,  195,  230,  198,
      215,  215,  215,  216,  216,  216,  207,  223,  210,  228,

      234,  200,  206,  211,  219,  236,  212,  217,  217,  217,
      213,  238,  238,  238,  242,  223,  249,  278,  228,  277,
      230,  276,  269,  236,  239,  239,  239,  268,  222,  240,
      240,  240,  258,  258,  258,  259,  259,  259,  267,  266,
      242,  265,  234,  263,  262,  249,  260,  260,  260,  270,
      270,  270,  271,  271,  271,  272,  272,  272,  279,  279,
      279,  280,  280,  280,  281,  281,  281,  285,  285,  285,
      286,  286,  286,  287,  287,  287,  290,  290,  290,  291,
      291,  291,  292,  292,  292,  293,  293,  293,  294,  294,
      294,  295,  295,  295,  296,  296,  296,  297,  297,  297,

      298,  298,  298,  299,  299,  299,  300,  300,  300,  302,
      302,  261,  302,  304,  304,  304,  305,  305,  257,  305,
      256,  255,  254,  252,  251,  248,  245,  244,  241,  235,
      232,  231,  229,  227,  226,  224,  221,  220,  218,  214,
      209,  208,  205,  204,  203,  202,  201,  197,  196,  194,
      190,  188,  184,  179,  176,  169,  167,  165,  164,  161,
      149,  148,  143,  142,  134,  121,  120,  112,  111,  107,
       99,   89,   72,   71,   66,   65,   57,   56,   55,   54,
       53,   50,   46,   28,   25,   23,   13,   12,   11,    9,
        3,  301,  301,  301,  301,  301,  301,  301,  301,  301,

      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1807091.l"
#define INITIAL 0
#line 21 "1807091.l"
	#include "1807091.tab.h"
	#include <stdio.h>
	#include <stdlib.h>
	#include <string.h>
	int varindex(char *var);
	extern int yylex();
	extern int yyparse();
	extern FILE *yyin;
	extern FILE *yyout;
	lineNo=1;
#line 621 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 33 "1807091.l"



#line 776 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 302 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 592 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 36 "1807091.l"
{ printf("single line comment\n"); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 37 "1807091.l"
{ printf("multiple_line_comment\n"); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 40 "1807091.l"
{ return MAIN_FN; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 41 "1807091.l"
{ return DEF; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "1807091.l"
{ return INT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 47 "1807091.l"
{ return FLOAT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 48 "1807091.l"
{ return CHAR; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 49 "1807091.l"
{ return DOUBLE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 50 "1807091.l"
{ return STRING; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 56 "1807091.l"
{ return INC; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 57 "1807091.l"
{ return DEC; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 58 "1807091.l"
{ return NOT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 61 "1807091.l"
{ printf("Logical Operator "); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 67 "1807091.l"
{ return '('; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 68 "1807091.l"
{ return ')'; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 69 "1807091.l"
{ return '{'; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 70 "1807091.l"
{ return '}'; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 71 "1807091.l"
{ return '['; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 72 "1807091.l"
{ return ']'; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 73 "1807091.l"
{ return END; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 74 "1807091.l"
{ return ','; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 78 "1807091.l"
{ return BREAK; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 79 "1807091.l"
{ return CONT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 80 "1807091.l"
{ return CASE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 81 "1807091.l"
{ return SWITCH;	}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 82 "1807091.l"
{ return DEFAULT;	}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 88 "1807091.l"
{ return WHILE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 89 "1807091.l"
{ return FOR; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 90 "1807091.l"
{ return POS_STEP; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 91 "1807091.l"
{ return NEG_STEP; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 100 "1807091.l"
{ return IF; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 101 "1807091.l"
{ return ELIF; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 102 "1807091.l"
{ return ELSE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 105 "1807091.l"
{ return ':';}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 111 "1807091.l"
{ return '+'; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 112 "1807091.l"
{ return '-'; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 113 "1807091.l"
{ return '*'; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 114 "1807091.l"
{ return '/'; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 115 "1807091.l"
{ return '^'; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 116 "1807091.l"
{ return MOD; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 117 "1807091.l"
{ return '='; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 122 "1807091.l"
{ return LT; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 123 "1807091.l"
{ return GT;; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 124 "1807091.l"
{ return EQEQ; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 125 "1807091.l"
{ return GEQ; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 126 "1807091.l"
{ return LEQ; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 127 "1807091.l"
{ return NEQ; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 133 "1807091.l"
{ return SIN; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 134 "1807091.l"
{ return COS; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 135 "1807091.l"
{ return TAN; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 136 "1807091.l"
{ return LN; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 137 "1807091.l"
{ return LOG10; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 138 "1807091.l"
{ return ODDEVEN; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 139 "1807091.l"
{ return FACTORIAL;  }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 140 "1807091.l"
{ return MAX; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 141 "1807091.l"
{ return MIN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 142 "1807091.l"
{ return PRIME; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 145 "1807091.l"
{ return WRITE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 146 "1807091.l"
{ return READ; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 149 "1807091.l"
{ 
						yylval.string = strdup(yytext);
					  	return STRING;
					}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 154 "1807091.l"
{ 
						yylval.flt = atof(yytext);
					  	return DOUBLE;
 					}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 159 "1807091.l"
{
						yylval.num = atoi(yytext);
					  	return NUMBER;
					}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 163 "1807091.l"
{
						yylval.num=atoi(yytext);
						return NUMBER;
					}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 169 "1807091.l"
;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 170 "1807091.l"
{lineNo++;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 172 "1807091.l"
{ return IMPORT; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 173 "1807091.l"
{ return HEADER; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 174 "1807091.l"
{ 
	// printf("%s helloo \n",yytext);
	yylval.string = strdup(yytext);
	return VARIABLE; 
	}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 184 "1807091.l"
ECHO;
	YY_BREAK
#line 1220 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 302 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 302 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 301);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 184 "1807091.l"


/* user subroutines */

int yywrap()
{
	return 1;
}

int main()
{
	
	yyin = freopen("input.txt","r",stdin);
	yyout = freopen("output.txt","w",stdout);
	yyparse();
	return 0;
	
}